# Copyright 2020 The Knative Authors.
# SPDX-License-Identifier: Apache-2.0

# This file is manually placed. Not using github.com/knative-extensions/knobots
# The reasons are outlined in https://github.com/knative/infra/issues/207
# Explaination of options https://github.com/reviewdog/action-shellcheck

name: shellcheck_reviewdog

on:
  pull_request:
    branches: [ 'main', 'release-*' ]

jobs:
  shellcheck:
    name: "manual / shellcheck"
    description: "Uses reviewdog to suggest shell script format changes. Enforces ShellCheck."
    runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: "ShellCheck"
            uses: reviewdog/action-shellcheck@v1
            with:
              reporter: 'github-pr-review'
              pattern: "*.sh"
              filter_mode: 'diff_context'
              exclude: |
                ./vendor/*
                */vendor/*
              shellcheck_flags: |
                --external-sources -e=SC1091
